var filterdata = {
  genre1: 'game',
  genre2: 'music',
  genre3: 'live',
  history1: [7, 3, 10],
  descript1: [5, 4, 10, 9],
}


var videosdata = [
    {
      idx: 3,
      user_id: 'mbc_sports',
      user_name: '연놀부',
      file_name: 'p1.jpg',
      content_title: '높았던 브라질의 벽',
      profile: 'pro1.jpg',
      likes: 1,
      genre: 'game',
    },
    {
      idx: 2,
      user_id: '음악이좋앙',
      user_name: '심청',
      file_name: 'p2.jpg',
      content_title: '추억의 책장을 넘기면',
      profile: 'pro2.jpg',
      likes: 3,
      genre: 'music',
    },
    {
      idx: 1,
      user_id: '스타이슈',
      user_name: '김삿갓',
      file_name: 'p3.jpg',
      content_title: '흥민이의 집',
      profile: 'pro3.jpg',
      likes: 2,
      genre: 'music',
    },
    {
      idx: 6,
      user_id: 'TickTok',
      user_name: '콩쥐',
      file_name: 'p4.jpg',
      content_title: '틱톡사용법',
      profile: 'pro4.jpg',
      likes: 5,
      genre: 'game',
    },
    {
      idx: 7,
      user_id: '오마이뉴스',
      user_name: '연흥부',
      file_name: 'p5.jpg',
      content_title: '외신 질문에 대응하는 손흥민',
      profile: 'pro5.jpg',
      likes: 9,
      genre: 'music',
    },
    {
      idx: 10,
      user_id: 'mediacop',
      user_name: '성춘향',
      file_name: 'p6.jpg',
      content_title: '성공의 3가지 방법',
      profile: 'pro6.jpg',
      likes: 4,
      genre: 'live',
    },
    {
      idx: 9,
      user_id: 'KBS_K-pop',
      user_name: '임꺽정',
      file_name: 'p7.jpg',
      content_title: '구글의 광고 활용법',
      profile: 'pro7.jpg',
      likes: 7,
      genre: 'music',
    },
    {
      idx: 8,
      user_id: 'TvN',
      user_name: '패캠',
      file_name: 'p8.jpg',
      content_title: '보이는 라디오 쇼 10회',
      profile: 'pro8.jpg',
      likes: 2,
      genre: 'live',
    },
    {
      idx: 4,
      user_id: 'KbsN_Sports',
      user_name: '홍길동',
      file_name: 'p9.jpg',
      content_title: '불후의 명곡 "김기태"',
      profile: 'pro9.jpg',
      likes: 4,
      genre: 'live',
    },
     {
      idx: 5,
      user_id: 'CPBC News',
      user_name: '김김김',
      file_name: 'p10.jpg',
      content_title: '국가자격증 받고 취업까지!',
      profile: 'pro10.jpg',
      likes: 4,
      genre: 'live',
    }
  ]